export type {
  CollectionSocialLoginConfig,
  CreateSocialAuthEndpointsArgs,
  FindUserCallback,
  FindUserCallbackArgs,
  GoogleProviderConfig,
  GoogleProviderSpecific,
  GoogleUserInfoProfile,
  MicrosoftGraphMeProfile,
  MicrosoftProviderConfig,
  MicrosoftProviderSpecific,
  PayloadSimpleSocialLoginConfig,
  ProviderConfig,
  SocialAuthErrorCode,
  SocialAuthOnError,
  SocialAuthOnErrorArgs,
  SocialAuthOnSuccess,
  SocialAuthOnSuccessArgs,
  SocialLoginUser,
  SocialProviderId,
  SocialProviderProfile,
} from '../types.js'
